# action.yml
name: 'ECS deploy'
description: 'Github action using fabfuel/ecs-deploy script for ecs deployments'
inputs:
    args: 
        description: 'Args to pass into ecs script'
        required: true
outputs:
    result:
        description: 'Output provided by ecs deploy tool'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}